version: '3.8'

services:
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DEBUG=True
    volumes:
      - ../../backend/app:/app/app
      - logs_data:/app/logs
    restart: unless-stopped
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vendperto_local
      POSTGRES_USER: vendperto_local
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  logs_data: